services:
  node1:
    build: ./node
    environment:
      - NODE_ID=node1
      - PORT=8001
      - PEERS=http://node2:8002,http://node3:8003
      - ANTI_ENTROPY_INTERVAL=3
    ports:
      - "8001:8001"

  node2:
    build: ./node
    environment:
      - NODE_ID=node2
      - PORT=8002
      - PEERS=http://node1:8001,http://node3:8003
      - ANTI_ENTROPY_INTERVAL=3
    ports:
      - "8002:8002"

  node3:
    build: ./node
    environment:
      - NODE_ID=node3
      - PORT=8003
      - PEERS=http://node1:8001,http://node2:8002
      - ANTI_ENTROPY_INTERVAL=3
    ports:
      - "8003:8003"
